services:
  - type: web
    name: krumly-backend
    env: node
    region: oregon
    buildCommand: cd backend && npm install --legacy-peer-deps && npx prisma generate && npm run build
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
